pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/dq-jira-s3-backup
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    when:
      event: push